module Financial
  class BankOfAmericaChargeRules
    def self.rules
      [
        [['angie', 'expenses'],         /glodence/i],
        [['angie', 'expenses'],         /juut/i],
        [['angie', 'expenses'],         /local yarn/i],
        [['angie', 'expenses'],         /macy/i],
        [['angie', 'expenses'],         /wearwellow/i, { description: 'Wearwellow - Clothing' }],
        [['auto', 'gas'],               /aarons grocery/i],
        [['auto', 'gas'],               /caseys/i],
        [['auto', 'gas'],               /cenex/i],
        [['auto', 'gas'],               /e&g/i],
        [['auto', 'gas'],               /elk river gas/i],
        [['auto', 'gas'],               /holiday/i],
        [['auto', 'gas'],               /kwik trip/i],
        [['auto', 'gas'],               /marathon/i],
        [['auto', 'gas'],               /simonson/i],
        [['auto', 'gas'],               /moreys markets/i],
        [['auto', 'parking'],           /fnp parking/i],
        [['auto', 'parking'],           /united.*childrens/i],
        [['clothing'],                  /talbots/i],
        [['entertainment'],             /admiral ds/i],
        [['entertainment'],             /agra culture/i],
        [['entertainment'],             /alma/i],
        [['entertainment'],             /anchor fish/i],
        [['entertainment'],             /barbette/i],
        [['entertainment'],             /boludo/i],
        [['entertainment'],             /d brian/i],
        [['entertainment'],             /the briar/i],
        [['entertainment'],             /brookside bar/i],
        [['entertainment'],             /cafe latte/i],
        [['entertainment'],             /can can wonderland/i],
        [['entertainment'],             /cedar cultural/i],
        [['entertainment'],             /city of st paul como dona/i],
        [['entertainment'],             /classic cookie/i],
        [['entertainment'],             /coconut/i],
        [['entertainment'],             /connys/i],
        [['entertainment'],             /cook st paul/i],
        [['entertainment'],             /cork & cask/i],
        [['entertainment'],             /due focacceria/i],
        [['entertainment'],             /eastsidepizzeria/i],
        [['entertainment'],             /el burrito mercado/i],
        [['entertainment'],             /film society of minn/i],
        [['entertainment'],             /finnish/i],
        [['entertainment'],             /fitzgeralds/i, { description: 'Handsome Hog' }],
        [['entertainment'],             /good life/i],
        [['entertainment'],             /hen house/i],
        [['entertainment'],             /hola arepa/i],
        [['entertainment'],             /holiday inn/i],
        [['entertainment'],             /howe daily kitch/i],
        [['entertainment'],             /italian pie shoppe/i],
        [['entertainment'],             /jefe/i],
        [['entertainment'],             /johns pizza/i],
        [['entertainment'],             /magnolias/i],
        [['entertainment'],             /marc heu/i],
        [['entertainment'],             /marios/i],
        [['entertainment'],             /merlins rest/i],
        [['entertainment'],             /minneapolis institute/i],
        [['entertainment'],             /mpls minneapolis/i, { description: 'MPLS - on street parking' }],
        [['entertainment'],             /nouvelle brewing/i],
        [['entertainment'],             /onstreet/i, { description: 'on street parking' }],
        [['entertainment'],             /peacock/i],
        [['entertainment'],             /pizza luce/i],
        [['entertainment'],             /pizzeria lola/i],
        [['entertainment'],             /red wagon/i],
        [['entertainment'],             /relish/i],
        [['entertainment'],             /rustica/i],
        [['entertainment'],             /sarnas/i],
        [['entertainment'],             /shaughnessy/i],
        [['entertainment'],             /smash park/i],
        [['entertainment'],             /spicy feta/i],
        [['entertainment'],             /st. james hotel/i],
        [['entertainment'],             /st paul brewing/i],
        [['entertainment'],             /swede hollow/i],
        [['entertainment'],             /taco libre/i],
        [['entertainment'],             /the mill/i],
        [['entertainment'],             /tommy chicagos pizza/i],
        [['exercise'],                  /ymca/i],
        [['gifts'],                     /accentric & european/i, { description: 'Depot - Waite Park' }],
        [['grocery'],                   /brents fresh foods red lake fall/i],
        [['grocery'],                   /cub foods/i],
        [['grocery'],                   /farmers store/i],
        [['grocery'],                   /kowalski/i],
        [['grocery'],                   /lunds/i],
        [['grocery'],                   /mississippi market/i],
        [['grocery'],                   /seward/i],
        [['grocery'],                   /surdyks/i],
        [['grocery'],                   /tim and toms speedy mark/i],
        [['grocery'],                   /toasted/i],
        [['grocery'],                   /total wine/i],
        [['healthcare'],                /mhlthfv/i, { description: 'MHealth Fairview' }],
        [['healthcare'],                /m hlth fv/i, { description: 'MHealth Fairview' }],
        [['healthcare'],                /valley eye clinic/i, { description: 'MHealth Fairview' }],
        [['home', 'expenses'],          /ace hardware/i],
        [['home', 'expenses'],          /amzn mktp/i],
        [['home', 'expenses'],          /apple store/i],
        [['home', 'expenses'],          /costco/i],
        [['home', 'expenses'],          /frattallones/i],
        [['home', 'expenses'],          /hobby lobby/i],
        [['home', 'expenses'],          /home depot/i],
        [['home', 'expenses'],          /lilydale garden center/i],
        [['home', 'expenses'],          /mann lake/i, { description: 'Mann Lake - Candle Making Stuff' }],
        [['home', 'expenses'],          /menards/i],
        [['home', 'expenses'],          /michaels/i],
        [['home', 'expenses'],          /mn driver and vehicle/i],
        [['home', 'expenses'],          /office depot/i],
        [['home', 'expenses'],          /samsonite/i],
        [['home', 'expenses'],          /subtext/i],
        [['home', 'expenses'],          /target/i],
        [['home', 'expenses'],          /target/i],
        [['home', 'expenses'],          /tru earth/i, { description: 'Tru Earth - Laundry Strips' }],
        [['home', 'expenses'],          /walgreens/i],
        [['home', 'expenses'],          /who gives a crap/i],
        [['home', 'expenses', 'yard'],  /mother earth gardens/i],
        [['home', 'expenses', 'yard'],  /urbans farm & greenh/i],
        [['languages'],                 /apple\.com/i, { price_range: (-23.00)..(-21.00), description: 'pimsleur' }],
        [['misc'],                      /foreign transaction fee/i],
        [['news'],                      /adamtooze/i],
        [['news'],                      /the athletic/i],
        [['news'],                      /compact magazine/i],
        [['news'],                      /dissenter/i],
        [['news'],                      /ettingermentum/i],
        [['news'],                      /feedbin/i],
        [['news'],                      /first look media/i],
        [['news'],                      /freddiedeboer/i],
        [['news'],                      /future crunch/i],
        [['news'],                      /intercept/i],
        [['news'],                      /kelton/i],
        [['news'],                      /krystal and saagar/i],
        [['news'],                      /heatmap/i],
        [['news'],                      /lever/i],
        [['news'],                      /means tv/i],
        [['news'],                      /mental hellth/i],
        [['news'],                      /mondoweiss/i],
        [['news'],                      /nation/i],
        [['news'],                      /pioneer press/i],
        [['news'],                      /recombobulation area/i],
        [['news'],                      /tyt/i],
        [['news'],                      /unicorn riot/i],
        [['news'],                      /wideleft/i],
        [['news'],                      /yasha levine/i],
        [['payment'],                   /ba electronic payment/i],
        [['phone'],                     /tmobile/i],
        [['politics', 'donation'],      /350.org/i],
        [['politics', 'donation'],      /actblue/i],
        [['politics', 'donation'],      /mn350/i],
        [['politics', 'donation'],      /democratic socialists/i],
        [['politics', 'donation'],      /doctors w\/o border/i],
        [['politics', 'donation'],      /greenpeace/i],
        [['politics', 'donation'],      /nelsieyang/i],
        [['politics', 'donation'],      /matriarch/i],
        [['politics', 'donation'],      /peta/i],
        [['politics', 'donation'],      /progressive internat/i],
        [['politics', 'donation'],      /rocket dollar/i],
        [['services', 'computer'],      /amazon web services/i],
        [['services', 'computer'],      /apple/i, { price_range: (-2.99)..(-2.99), description: 'icloud' }],
        [['services', 'computer'],      /dreamhost/i],
        [['services', 'computer'],      /dropbox/i],
        [['services', 'computer'],      /evernote/i],
        [['services', 'computer'],      /heroku/i],
        [['services', 'computer'],      /jetbrains/i],
        [['services', 'computer'],      /twilio/i],
        [['services', 'computer'],      /zoom/i],
        [['services', 'home', 'internet'],   /quantum fiber/i],
        [['services', 'home', 'security'],   /adt/i],
        [['steve', 'expenses'],         /abogados/i],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-1.00)..(0.00), description: 'storage' }],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-5.00)..(-4.00), description: 'mlb.tv' }],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-110.00)..(-100.00), description: 'nfl' }],
        [['steve', 'expenses'],         /backstory/i],
        [['steve', 'expenses'],         /bully brew/i],
        [['steve', 'expenses'],         /cafe ceres/i],
        [['steve', 'expenses'],         /caydence/i],
        [['steve', 'expenses'],         /cedarholm/i],
        [['steve', 'expenses'],         /claddagh/i],
        [['steve', 'expenses'],         /dogwood/i],
        [['steve', 'expenses'],         /emery/i, { description: 'Spyhouse Downtown'}],
        [['steve', 'expenses'],         /groundswell/i],
        [['steve', 'expenses'],         /half price/i],
        [['steve', 'expenses'],         /kindle/i],
        [['steve', 'expenses'],         /minnesota wld/i],
        [['steve', 'expenses'],         /nina/i],
        [['steve', 'expenses'],         /rock creek coffee/i],
        [['steve', 'expenses'],         /starbucks/i],
        [['steve', 'expenses'],         /spyhouse/i],
        [['transportation'],            /metro trans/i],
        [['transportation'],            /hourcar/i],
        [['transportation'],            /apple\.com/i, { price_range: (-27.00)..(-26.00), description: 'Transit App' }],
        [['travel'],                    /allianz/i],
        [['travel'],                    /airbnb/i],
        [['travel'],                    /americinn/i],
        [['travel'],                    /united/i],
        [['tv'],                        /apple\.com/i, { price_range: (-11.00)..(-7.00), description: 'Apple TV+' }],
        [['tv'],                        /prime/i],
        [['tv'],                        /britbox/i],
        [['tv'],                        /hulu/i],
        [['tv'],                        /netflix/i],
        [['tv'],                        /peacock/i],
        [['tv'],                        /pbs/i],
        [['tv'],                        /spotify/i],
      ]
    end
  end
end