module Financial
  class BankOfAmericaChargeRules
    def self.rules
      [
        [['angie', 'expenses'],         /glodence/i],
        [['angie', 'expenses'],         /juut/i],
        [['angie', 'expenses'],         /local yarn/i],
        [['angie', 'expenses'],         /macy/i],
        [['angie', 'expenses'],         /sp mouth watchers/i],
        [['angie', 'expenses'],         /sp zellies/i],
        [['angie', 'expenses'],         /wearwellow/i, { description: 'Wearwellow - Clothing' }],
        [['auto', 'gas'],               /aarons grocery/i],
        [['auto', 'gas'],               /arco.*rothsay/i],
        [['auto', 'gas'],               /bp#/i],
        [['auto', 'gas'],               /caseys/i],
        [['auto', 'gas'],               /cenex/i],
        [['auto', 'gas'],               /circle\s*k/i],
        [['auto', 'gas'],               /cromwell self service/i],
        [['auto', 'gas'],               /e&g/i],
        [['auto', 'gas'],               /elk river gas/i],
        [['auto', 'gas'],               /holiday/i],
        [['auto', 'gas'],               /krist oil/i],
        [['auto', 'gas'],               /kwik trip/i],
        [['auto', 'gas'],               /marathon/i],
        [['auto', 'gas'],               /shell oil/i],
        [['auto', 'gas'],               /simonson/i],
        [['auto', 'gas'],               /speedway/i],
        [['auto', 'parking'],           /fnp parking/i],
        [['auto', 'parking'],           /united.*childrens/i],
        [['charity'],                   /gofundme/i],
        [['clothing'],                  /schuler shoes/i],
        [['clothing'],                  /talbots/i],
        [['clothing'],                  /von maur/i],
        [['entertainment'],             /admiral ds/i],
        [['entertainment'],             /agra culture/i],
        [['entertainment'],             /alma/i],
        [['entertainment'],             /anchor fish/i],
        [['entertainment'],             /atomifargo/i, { description: 'Atomic Coffee - Fargo' }],
        [['entertainment'],             /aspen lodge grand marais/i],
        [['entertainment'],             /babas llc/i],
        [['entertainment'],             /barbette/i],
        [['entertainment'],             /bina minneapolis/i],
        [['entertainment'],             /black sheep/i],
        [['entertainment'],             /boludo/i],
        [['entertainment'],             /d brian/i],
        [['entertainment'],             /the briar/i],
        [['entertainment'],             /bridgestone bar/i],
        [['entertainment'],             /brookside bar/i],
        [['entertainment'],             /brunson/i, { description: 'Brunson\'s - Pub' }],
        [['entertainment'],             /burntchicken/i],
        [['entertainment'],             /cafe latte/i],
        [['entertainment'],             /can can wonderland/i],
        [['entertainment'],             /cantabria coffee/i, { description: 'Cantabri Coffee - Bemidji Coffee Shop' }],
        [['entertainment'],             /cedar cultural/i],
        [['entertainment'],             /charras & tequila/i],
        [['entertainment'],             /city of st paul como dona/i],
        [['entertainment'],             /classic cookie/i],
        [['entertainment'],             /coconut/i],
        [['entertainment'],             /connys/i],
        [['entertainment'],             /cook st paul/i],
        [['entertainment'],             /copper kitchen/i],
        [['entertainment'],             /cork & cask/i],
        [['entertainment'],             /craft brewhaus llc hallock/i],
        [['entertainment'],             /crosby bakery grand marais/i],
        [['entertainment'],             /due focacceria/i],
        [['entertainment'],             /eagles club/i],
        [['entertainment'],             /eastsidepizzeria/i],
        [['entertainment'],             /element wood fire/i],
        [['entertainment'],             /el burrito mercado/i],
        [['entertainment'],             /el tequila mexican/i],
        [['entertainment'],             /elior - coliseum/i, { description: 'State Fair Food' }],
        [['entertainment'],             /film society of minn/i],
        [['entertainment'],             /finnish/i],
        [['entertainment'],             /first avenue/i],
        [['entertainment'],             /fitzgeralds/i, { description: 'Handsome Hog' }],
        [['entertainment'],             /good life/i],
        [['entertainment'],             /green door/i],
        [['entertainment'],             /gun flint tavern/i],
        [['entertainment'],             /hen house/i],
        [['entertainment'],             /hola arepa/i],
        [['entertainment'],             /holiday inn/i],
        [['entertainment'],             /howe daily kitch/i],
        [['entertainment'],             /iron ranger/i],
        [['entertainment'],             /italian pie shoppe/i],
        [['entertainment'],             /jefe/i],
        [['entertainment'],             /jets pizza/i],
        [['entertainment'],             /john.*s.*pizza/i],
        [['entertainment'],             /joy studio fargo/i, { description: 'Clothing Store - Fargo' }],
        [['entertainment'],             /kobo/i],
        [['entertainment'],             /kyatchi/i],
        [['entertainment'],             /mn brewers guild/i, { description: 'State Fair Beer Flights' }],
        [['entertainment'],             /la delicious bread/i],
        [['entertainment'],             /leos grill & malt shop/i],
        [['entertainment'],             /lolo american kitchen/i],
        [['entertainment'],             /lost fox/i],
        [['entertainment'],             /magnolias/i],
        [['entertainment'],             /marc heu/i],
        [['entertainment'],             /marine general store/i],
        [['entertainment'],             /marios/i],
        [['entertainment'],             /merlins rest/i],
        [['entertainment'],             /midtown exchange/i],
        [['entertainment'],             /mikeys spirits smiles hallock/i],
        [['entertainment'],             /minnesota farmers union/i],
        [['entertainment'],             /minneapolis institute/i],
        [['entertainment'],             /minnesota state parks/i],
        [['entertainment'],             /mpls minneapolis/i, { description: 'MPLS - on street parking' }],
        [['entertainment'],             /mt snelling and como/i, { description: 'State Fair Vendor??' }],
        [['entertainment'],             /naughty doner/i],
        [['entertainment'],             /nicos tacos/i],
        [['entertainment'],             /nouvelle brewing/i],
        [['entertainment'],             /onstreet/i, { description: 'on street parking' }],
        [['entertainment'],             /owamni/i],
        [['entertainment'],             /perfect coffee/i],
        [['entertainment'],             /pizza luce/i],
        [['entertainment'],             /pizzeria lola/i],
        [['entertainment'],             /bbq state fair/i, { description: 'RC BBQ State Fair' }],
        [['entertainment'],             /red wagon/i],
        [['entertainment'],             /relish/i],
        [['entertainment'],             /riverfront ramp/i, { description: 'Guthrie Parking Ramp' }],
        [['entertainment'],             /rothsay truck stop/i],
        [['entertainment'],             /rustica/i],
        [['entertainment'],             /saint paul parking/i, { description: 'StP - on street parking' }],
        [['entertainment'],             /sarnas/i],
        [['entertainment'],             /shaughnessy/i],
        [['entertainment'],             /smash park/i],
        [['entertainment'],             /sonny.*cafe/i],
        [['entertainment'],             /spicy feta/i],
        [['entertainment'],             /stockholm pie/i],
        [['entertainment'],             /st. james hotel/i],
        [['entertainment'],             /st paul brewing/i],
        [['entertainment'],             /swede hollow/i],
        [['entertainment'],             /szechuan/i],
        [['entertainment'],             /taco libre/i],
        [['entertainment'],             /that.*s a wrap/i, { description: 'That\'s a Wrap - Hallock Food Truck' }],
        [['entertainment'],             /the hangar/i],
        [['entertainment'],             /the mill/i],
        [['entertainment'],             /tommy chicagos pizza/i],
        [['entertainment'],             /und.parking passport/i],
        [['entertainment'],             /villa bellezza winerypepin wi/i],
        [['entertainment'],             /vineland ramp/i, { description: 'The Walker Parking' }],
        [['entertainment'],             /voyageur brewing/i],
        [['entertainment'],             /walker cafe/i],
        [['entertainment'],             /white horse rest/i],
        [['exercise'],                  /ymca/i],
        [['gifts'],                     /accentric & european/i, { description: 'Depot - Waite Park' }],
        [['gifts'],                     /barnes/i],
        [['gifts'],                     /bloomery/i],
        [['gifts'],                     /boreal/i],
        [['gifts'],                     /corazon/i],
        [['gifts'],                     /north house folk school/i],
        [['grocery'],                   /breadsmith/i],
        [['grocery'],                   /brents fresh foods red lake fall/i],
        [['grocery'],                   /cook county co-op/i],
        [['grocery'],                   /cub foods/i],
        [['grocery'],                   /cub liquo/i],
        [['grocery'],                   /diamond city bread/i],
        [['grocery'],                   /dollar general/i],
        [['grocery'],                   /everyday 38567001 robbinsdale/i, { description: 'Cub Foods - Robbinsdale' }],
        [['grocery'],                   /farmers store/i],
        [['grocery'],                   /gene.*foods/i],
        [['grocery'],                   /hy-vee/i],
        [['grocery'],                   /johnson.*foods/i],
        [['grocery'],                   /kowalski/i],
        [['grocery'],                   /lunds/i],
        [['grocery'],                   /millers fresh foods/i],
        [['grocery'],                   /mississippi market/i],
        [['gracery'],                   /moreys markets/i],
        [['grocery'],                   /morey.*seafood/i],
        [['grocery'],                   /robbinsdale wine/i],
        [['grocery'],                   /seward/i],
        [['grocery'],                   /surdyks/i],
        [['grocery'],                   /thielen meats/i],
        [['grocery'],                   /tim and toms speedy mark/i],
        [['grocery'],                   /toasted/i],
        [['grocery'],                   /total wine/i],
        [['healthcare'],                /med\*fairview/i, { description: 'MHealth Fairview' }],
        [['healthcare'],                /mhlthfv/i, { description: 'MHealth Fairview' }],
        [['healthcare'],                /m hlth fv/i, { description: 'MHealth Fairview' }],
        [['healthcare'],                /north memorial parking/i],
        [['healthcare'],                /pet poison helpline/i],
        [['healthcare'],                /valley eye clinic/i, { description: 'MHealth Fairview' }],
        [['healthcare'],                /west 7th dental/i],
        [['home', 'expenses'],          /ace hardware/i],
        [['home', 'expenses'],          /amzn mktp/i],
        [['home', 'expenses'],          /apple store/i],
        [['home', 'expenses'],          /ben franklin/i],
        [['home', 'expenses'],          /cooks of crocus hill/i],
        [['home', 'expenses'],          /costco/i],
        [['home', 'expenses'],          /frattallones/i],
        [['home', 'expenses'],          /gullander/i],
        [['home', 'expenses'],          /hardware hank/i],
        [['home', 'expenses'],          /hobby lobby/i],
        [['home', 'expenses'],          /home depot/i],
        [['home', 'expenses'],          /lilydale garden center/i],
        [['home', 'expenses'],          /mann lake/i, { description: 'Mann Lake - Candle Making Stuff' }],
        [['home', 'expenses'],          /menards/i],
        [['home', 'expenses'],          /michaels/i],
        [['home', 'expenses'],          /mn driver and vehicle/i],
        [['home', 'expenses'],          /office depot/i],
        [['home', 'expenses'],          /payrange mobile/i, { description: 'PayRange - Laundry' }],
        [['home', 'expenses'],          /restaurant depot/i],
        [['home', 'expenses'],          /samsonite/i],
        [['home', 'expenses'],          /subtext/i],
        [['home', 'expenses'],          /target/i],
        [['home', 'expenses'],          /tickpick/i],
        [['home', 'expenses'],          /tru earth/i, { description: 'Tru Earth - Laundry Strips' }],
        [['home', 'expenses'],          /wal-mart/i],
        [['home', 'expenses'],          /walgreens/i],
        [['home', 'expenses'],          /who gives a crap/i],
        [['home', 'expenses', 'yard'],  /mother earth gardens/i],
        [['home', 'expenses', 'yard'],  /urbans farm & greenh/i],
        [['invalid'],                   /rahrah/i],
        [['languages'],                 /apple\.com/i, { price_range: (-24.00)..(-21.00), description: 'pimsleur' }],
        [['misc'],                      /foreign transaction fee/i],
        [['misc'],                      /usps/i],
        [['misc'],                      /nothingbutvocab/i],
        [['news'],                      /adamtooze/i],
        [['news'],                      /alon mizrahi/i],
        [['news'],                      /the appeal/i],
        [['news'],                      /the athletic/i],
        [['news'],                      /black panther paper/i],
        [['news'],                      /compact magazine/i],
        [['news'],                      /current affairs/i],
        [['news'],                      /dissenter/i],
        [['news'],                      /drop site/i],
        [['news'],                      /ettingermentum/i],
        [['news'],                      /feedbin/i],
        [['news'],                      /first look media/i],
        [['news'],                      /fix the news/i],
        [['news'],                      /freddiedeboer/i],
        [['news'],                      /future crunch/i],
        [['news'],                      /intercept/i],
        [['news'],                      /kelton/i],
        [['news'],                      /krystal and saagar/i],
        [['news'],                      /heatmap/i],
        [['news'],                      /lever/i],
        [['news'],                      /means tv/i],
        [['news'],                      /mental hellth/i],
        [['news'],                      /mondoweiss/i],
        [['news'],                      /nation/i],
        [['news'],                      /peterturchin/i],
        [['news'],                      /pioneer press/i],
        [['news'],                      /recombobulation area/i],
        [['news'],                      /status cou/i],
        [['news'],                      /tyt/i],
        [['news'],                      /unicorn riot/i],
        [['news'],                      /wideleft/i],
        [['news'],                      /yasha levine/i],
        [['payment'],                   /ba electronic payment/i],
        [['phone'],                     /tmobile/i],
        [['politics', 'donation'],      /350/i],
        [['politics', 'donation'],      /actblue/i],
        [['politics', 'donation'],      /democratic socialists/i],
        [['politics', 'donation'],      /doctors w\/o border/i],
        [['politics', 'donation'],      /doctorswithoutborders/i],
        [['politics', 'donation'],      /greenpeace/i],
        [['politics', 'donation'],      /nelsieyang/i],
        [['politics', 'donation'],      /GMN NORTH END COMM/i, { description: 'North End Giving Fund' }],
        [['politics', 'donation'],      /matriarch/i],
        [['politics', 'donation'],      /peta/i],
        [['politics', 'donation'],      /progressive int/i],
        [['politics', 'donation'],      /rocket dollar/i],
        [['politics', 'donation'],      /unrwa/i],
        [['services', 'computer'],      /amazon web services/i],
        [['services', 'computer'],      /apple/i, { price_range: (-2.99)..(-2.99), description: 'icloud' }],
        [['services', 'computer'],      /dreamhost/i],
        [['services', 'computer'],      /dropbox/i],
        [['services', 'computer'],      /element creations/i, { description: "element.io Matrix/Signal bridge"}],
        [['services', 'computer'],      /evernote/i],
        [['services', 'computer'],      /github/i],
        [['services', 'computer'],      /heroku/i],
        [['services', 'computer'],      /jetbrains/i],
        [['services', 'computer'],      /kagi/i],
        [['services', 'computer'],      /twilio/i],
        [['services', 'computer'],      /zoom/i],
        [['services', 'home', 'internet'],   /quantum fiber/i],
        [['services', 'home', 'security'],   /adt/i],
        [['steve', 'expenses'],         /2pscsaint saint paul/i, { description: 'St Paul Saints Game' }],
        [['steve', 'expenses'],         /abogados/i],
        [['steve', 'expenses'],         /ali baba grill/i],
        [['steve', 'expenses'],         /anchor iron/i, { description: 'State Fair Garden Animals' }],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-5.00)..(-2.00), description: 'storage' }],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-7.00)..(-5.00), description: 'mlb.tv' }],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-11.00)..(-9.00), description: 'APPLE unknown - 1' }],
        [['steve', 'expenses'],         /apple\.com/i, { price_range:(-110.00)..(-100.00), description: 'nfl' }],
        [['steve', 'expenses'],         /backstory/i],
        [['steve', 'expenses'],         /brits minneapolis/i],
        [['steve', 'expenses'],         /bully brew/i],
        [['steve', 'expenses'],         /cafe ceres/i],
        [['steve', 'expenses'],         /caffetto/i],
        [['steve', 'expenses'],         /cardigan donuts/i],
        [['steve', 'expenses'],         /caydence/i],
        [['steve', 'expenses'],         /cedarholm/i],
        [['steve', 'expenses'],         /claddagh/i],
        [['steve', 'expenses'],         /dogwood/i],
        [['steve', 'expenses'],         /emery/i, { description: 'Spyhouse Downtown'}],
        [['steve', 'expenses'],         /goodrichgolf/i],
        [['steve', 'expenses'],         /gray fox/i],
        [['steve', 'expenses'],         /groundswell/i],
        [['steve', 'expenses'],         /half price/i],
        [['steve', 'expenses'],         /karol coffee co/i],
        [['steve', 'expenses'],         /kathy.*live bait/i],
        [['steve', 'expenses'],         /kindle/i],
        [['steve', 'expenses'],         /lancaster riverside/i, { description: 'Lancaster Riverside Golf Course' }],
        [['steve', 'expenses'],         /minnesota wld/i],
        [['steve', 'expenses'],         /nafnafgrill/i],
        [['steve', 'expenses'],         /namaste cafe/i],
        [['steve', 'expenses'],         /nina/i],
        [['steve', 'expenses'],         /ninth street soccer/i],
        [['steve', 'expenses'],         /rei #42/i],
        [['steve', 'expenses'],         /rock creek coffee/i],
        [['steve', 'expenses'],         /roto sports/i, { description: 'rotowire' }],
        [['steve', 'expenses'],         /school space media/i, { description: "NSPN.tv -- prep sports" }],
        [['steve', 'expenses'],         /seagull outfitters/i],
        [['steve', 'expenses'],         /solera/i],
        [['steve', 'expenses'],         /starbucks/i],
        [['steve', 'expenses'],         /spyhouse/i],
        [['steve', 'expenses'],         /vitality roasting/i],
        [['transportation'],            /metro trans/i],
        [['transportation'],            /hourcar/i],
        [['transportation'],            /apple\.com/i, { price_range: (-25.00)..(-24.00), description: 'Transit App' }],
        [['travel'],                    /allianz/i],
        [['travel'],                    /airbnb/i],
        [['travel'],                    /americinn/i],
        [['travel'],                    /united/i],
        [['tv'],                        /apple\.com/i, { price_range: (-15.00)..(-12.00), description: 'Apple TV+' }],
        [['tv'],                        /prime/i],
        [['tv'],                        /britbox/i],
        [['tv'],                        /hulu/i],
        [['tv'],                        /netflix/i],
        [['tv'],                        /peacock/i],
        [['tv'],                        /pbs/i],
        [['tv'],                        /spotify/i],
      ]
    end
  end
end